
language: python
python: 3.7
install:
  - pip install mkdocs mkdocs-material pymdown-extensions pygments
before_script:
  - cd mindsdb-docs
#build docs  
scripts: mkdocs build --verbose --clean 
# deploy to github pages
before_script:
  - cd mindsdb-docs
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: site
    on:
      branch: master
      condition: $DEPLOYMENT_ENV = "true"
