language: python
python: 3.7
install:
  - pip install mkdocs
scripts: echo publish docs
#build docs
before_deploy:
  - cd mindsdb-docs
  - mkdocs build --verbose --clean --strict
 
# deploy to github pages
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: site
    on:
      branch: master
      condition: $DEPLOYMENT_ENV = "true"
