site_name: MindsDB
repo_name: 'mindsdb/mindsdb'
repo_url: 'https://github.com/mindsdb/mindsdb'
theme:
  name: 'material'
  palette:
    primary: '#00b06d'
    accent: '#00b06d'
plugins:
    - search:
        lang: 'en'
        social:
          - type: 'github'
            link: 'https://github.com/mindsdb/mindsdb'
          - type: 'twitter'
            link: 'https://twitter.com/mindsdb'
          - type: 'link'
            link: 'https://www.mindsdb.com'
markdown_extensions:
  - codehilite
  - admonition
nav:
  - Home: index.md
  - Config: Config.md