site_name: MindsDB
repo_name: 'mindsdb/mindsdb'
repo_url: 'https://github.com/mindsdb/mindsdb'
theme:
  name: 'material'
  palette:
    primary: 'green'
    accent: 'green'
  logo: assets/mdb_logo_w.svg
plugins:
    - search:
        lang: 'en'
        social:
          - type: 'github'
            link: 'https://github.com/mindsdb/mindsdb'
          - type: 'twitter'
            link: 'https://twitter.com/mindsdb'
          - type: 'link'
            link: 'https://www.mindsdb.com'
markdown_extensions:
  - codehilite
  - admonition
nav:
  - Home: index.md
  - Getting started:
    - Installing MindsDB: Installing.md
    - Google Colab: GoogleColab.md
    - Running on Jupyter Notebook: JupyterNotebook.md
  - Configuration:
    - Predictor interface: PredictorInterface.md
    - Configuration Settings: Config.md
  - Features:
    - Column metrics: features/ColumnMetrics.md
    - Data sources: features/DataSources.md
  - Comparisons:
    - Comparison with other Libraries: comparisons/ComparsionWithOtherLibraries.md
    - Comparing MindsDB accuracy: comparisons/AccuracyComparison.md
  - Integrations:
    - Amazon SageMaker: integrations/AwsSageMaker.md
  - Tutorials:
    - Basic Examples: tutorials/BasicExample.md
    - Advanced Examples: tutorials/AdvancedExamples.md
    - Financial Services:
      - Credit Scoring: tutorials/CreditScoring.md
  - Config: Config.md