site_name: MindsDB
repo_name: 'mindsdb/mindsdb'
repo_url: 'https://github.com/mindsdb/mindsdb'
theme:
  name: 'material'
  palette:
    primary: 'green'
    accent: 'green'
  logo: assets/mdb_logo_w.svg
plugins:
    - search:
        lang: 'en'
        social:
          - type: 'github'
            link: 'https://github.com/mindsdb/mindsdb'
          - type: 'twitter'
            link: 'https://twitter.com/mindsdb'
          - type: 'link'
            link: 'https://www.mindsdb.com'
markdown_extensions:
  - codehilite
  - admonition
nav:
  - Getting started:
    - Installing MindsDB: Installing.md
    - Google Colab: GoogleColab.md
    - Running on Jupyter Notebook: JupyterNotebook.md
  - Configuration:
    - Predictor interface: PredictorInterface.md
    - Configuration Settings: Config.md
  - Features:
    - Column metrics: features/ColumnMetrics.md
    - Data sources: features/DataSources.md
  - Comparisons:
    - Comparison with other Libraries: comparisons/ComparsionWithOtherLibraries.md
    - Comparing MindsDB accuracy: comparisons/AccuracyComparison.md
  - Integrations:
    - Amazon SageMaker: integrations/AwsSageMaker.md
    - Bring your own container:
      - MindsDB container: integrations/MindsDBSageContainer.md
      - Train and host MindsDB models: integrations/UseMindsDBinSage.md
      - Train and host MindsDB models using SageMaker SDK: integrations/SageMakerSDK.md
      - Invoke MindsDB endpoint on SageMaker: integrations/CallSageMakerEndpoint.md
  - Tutorials:
    - Basic Examples: tutorials/BasicExample.md
    - Advanced Examples: tutorials/AdvancedExamples.md
    - Advanced Use Cases:
      - High-Tech & Manufacturing:
        - Predictive Maintenance: PredictiveMaintenance.md
      - Financial Services:
        - Credit Scoring: tutorials/CreditScoring.md
      - Retail & Online:
        - Custiner Lifetime Value Optimization: tutorials/CustomerLifetimeValue.md
        - Fraud Detection: tutorials/FraudDetection.md
      - Health Care:
        - Patient Health: tutorials/PatientHealthOutcomes.md
        - Medical Diagnosis: tutorials/MedicalDiagnosis.md
      - Travel:
        - Hotel Booking Demand: tutorials/HotelBooking.md
      - Telecomunications:
        - Customer Churn Reduction: tutorials/
